production: &production
  :url: "redis://h:pbs1b85rfv1jmafru1fgs2fp6p5@ec2-54-83-205-71.compute-1.amazonaws.com:11439"
  :timeout: 1
development: &development
  :url: "redis://h:pbs1b85rfv1jmafru1fgs2fp6p5@ec2-54-83-205-71.compute-1.amazonaws.com:11439"
  :timeout: 1
  :inline: true
test: *development