development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: ENV["REDISTOGO"]
  :host: tarpon.redistogo.com
  :port: 10272
  :password: 10e348ac30ca0002879ce9d85daf0bb0
  :inline: true
  :timeout: 1

