development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://redistogo:0645024dda4cdc17e3a5cb2ca24b5885@tarpon.redistogo.com:11662/
  :host: tarpon.redistogo.com
  :port: 11662
  :password: 0645024dda4cdc17e3a5cb2ca24b5885
  :inline: true
  :timeout: 1


